### ISSUE TITLE
add about page

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-backend#16]
Describe Phoenicis for someone who doesn't know PoL/PoM 4 and explain the meaning of the name "Phoenicis".

https://github.com/PhoenicisOrg/phoenicis/blob/master/docs/_pages/home.md can be used as a starting point.

**Comment by plata** [comment]
I was thinking about something like this (screenshot from a Jekyll page which I made to showcase it):
![screenshot](https://user-images.githubusercontent.com/3973260/40269769-eca35110-5b82-11e8-9aa0-0c413613c6d8.png)

**Comment by qparis** [comment]
I like this idea

**Comment by plata** [comment]
Closed due to inactivity.
