### ISSUE TITLE
Forum broken

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis-backend#27]
Not sure where to post this, but the [forum](www.playonlinux.com/en/forums.html) seems to be broken (empty):

![grafik](https://user-images.githubusercontent.com/18488086/50296839-a2c7c380-047b-11e9-9225-b9d011e0f636.png)

**Comment by qparis** [comment]
Should be fixed. Can you confirm?

**Comment by plata** [comment]
Works for me.

**Comment by madoar** [comment]
Works for me too.

**Comment by qparis** [comment]
Ok, I'm refactoring the code of the website so that I can release most of the components. Takes time and it can have side effects like this. Feel free to alert me whenever there are other problems

**Comment by plata** [comment]
Ok. Btw looks much nicer already.

**Comment by madoar** [comment]
@qparis the navbar menu looks a little bit broken on my smartphone.
The "Supported software" and language entries are open by default, which shouldn't be the case in my opinion.
In addition the menu is only shown on the main homepage and not on a subpage like "News".

**Comment by qparis** [comment]
Yeah I’m aware of responsibleness problems. Can you open an issue to track it?

**Comment by madoar** [comment]
I will do so later
