### ISSUE TITLE
Fix GitHub security alerts

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-backend#28]

**Comment by plata** [comment]
I've enabled dependabot but it doesn't seem to work. Any ideas?

**Comment by plata** [comment]
@dependabot can you help me?

**Comment by plata** [comment]
@greysteil can you help?

**Comment by greysteil** [comment]
Sure thing - let me take a look

**Comment by greysteil** [comment]
Just dug in - it looks like you've given Dependabot access to `PhoenicisOrg` but haven't added this repo. If you go to https://app.dependabot.com/accounts/PhoenicisOrg/repos/123806126 you should be able to add it from there.

**Comment by plata** [comment]
Thanks. I absolutely wasn't aware of that page. I thought adding the repo to the dependabot settings in "Installed GitHub Apps" is sufficient. Could you maybe add a hint to this page that the repositories must be added on dependabot.com as well?

**Comment by greysteil** [comment]
No worries!

Frustratingly, we don't have any control over that page - it's all GitHub. We could do something when you're redirected back to Dependabot, though - I'll have a think about exactly what.

**Comment by plata** [comment]
Would be great!

I think GitHub should do something about this topic. Alternatively, you could maybe add a note to the dependabot description (this is the same like in marketplace, right?).

**Comment by ImperatorS79** [comment]
I have just received security alerts from this repository, without doing anything. Normal ?

**Comment by qparis** [comment]
Nope, we can merge the MR

**Comment by plata** [comment]
@ImperatorS79 I guess it's because you're member of the organization.

@qparis there's still one open alert about jetty.

**Comment by plata** [comment]
@qparis is the website updated automatically if this repo changes? If not, I would just merge the security fixes as soon as they show up.

**Comment by plata** [comment]
Closed due to inactivity.
