### ISSUE TITLE
"PlayOnLinux's Team" forum is visible when not logged in

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis-backend#32]
When you open the [forum page](https://www.playonlinux.com/en/forums.html) as a not logged in user you can see the subforum `PlayOnLinux's Team`, which I believe shouldn't be visible for not logged in users.

In addition when clicking on the said subforum you see the following:
![grafik](https://user-images.githubusercontent.com/18488086/50387941-b9cf1580-0708-11e9-8544-18687f868dab.png)

**Comment by qparis** [comment]
Should be fixed. Can you confirm?

**Comment by madoar** [comment]
The bug has been fixed.
