### ISSUE TITLE
Abstract: Phoenicis mediawiki.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis-backend#51]
Recommends making a mediawiki for phoenicis because it's user-friendy to update and supperior to https://phoenicisorg.github.io/phoenicis/ since it doesn't require making a Merge Request to update and browsing github repository.

Also recommends adapting my way of updating the wiki as follows:

Encourage end-users to update the wiki and if something is missing mark it as `{{stub|MESSAGE}}`. This shoudn't be visible by default and should help contributors to update the articles with all required info. 

I've maintained Gentoo Wiki with community for few months untill Grknight came and ruined it.. This approach allowed finishing lots of articles and ensuring that they have all required info.

Wiki should also have set guidelines to ensure quality of content provided + we should discourage long articles -> info should be provided as effective as possible.

If long descriptions are required they should be hidden by default. 

Users can also make their own documentation which is preffered by some (me included).

**Comment by qparis** [comment]
Already exists on playonlinux.com

**Comment by Kreyren** [comment]
@plata playonlinux != phoenicis afaik.. How much is it usable for phoenicis?

**Comment by qparis** [comment]
It is

**Comment by Kreyren** [comment]
@qparis noted, what about documentation with it and the way it's maintained?

**Comment by qparis** [comment]
I don't understand

**Comment by Kreyren** [comment]
@qparis I'm suggesting to make a wiki for phoenicis instead of using https://phoenicisorg.github.io/phoenicis/ which is less user-friendly and effective + interpreting wiki guideliness that allows adding comments in articles that are hidden by default and used for moderators and contributors for QA.

**Comment by Kreyren** [comment]
@qparis Ideally we would have some kind of reference with research on wiki to know that verb X on game Y has Z effect, etc.. + better instructions to write scripts and other info.

**Comment by qparis** [comment]
We are going to use pol.com wiki.

**Comment by Kreyren** [comment]
@qparis Seems insane assuming that POL5 is totally different program from POL4 which may creates a confusion assuming that POL4 documentation is kept.. Would suggest using new wiki.

What about suggested QA for data provided on wiki to be community maintained?

**Comment by qparis** [comment]
This is just a matter of structuration. Spreading the community is not sane either

**Comment by Kreyren** [comment]
> Spreading the community is not sane either

meaning?
